# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    base_path: "bundles/ckeditor"
    js_path:   "bundles/ckeditor/ckeditor.js"
    configs:
        main_config:
            allowedContent: true
            height: 850
            width: 1000
            codeSnippet_theme: 'monokai_sublime'
            codeSnippet_languages:
                {
                  html: 'HTML',
                  css: 'CSS',
                  javascript: 'Javascript',
                  json: 'JSON',
                  php: 'PHP',
                  sql: 'SQL',
                  xml: 'XML',
                  yaml: 'YAML',
                  bash: 'Bash',
                  shell: 'Shell'
                }
            toolbar:
                - {
                    name: "styles",
                    items: 
                      [
                        "Bold",
                        "Italic",
                        "Underline",
                        "Strike",
                        "CodeSnippet",
                        "Code",
                        "Blockquote",
                        "-",
                        "Link",
                        "-",
                        "RemoveFormat",
                        "NumberedList",
                        "BulletedList",
                        "-",
                        "Outdent",
                        "Indent",
                        "-",
                        "-",
                        "JustifyLeft",
                        "JustifyCenter",
                        "JustifyRight",
                        "JustifyBlock",
                        "-",
                        "Image",
                        "Table",
                        "-",
                        "TextColor",
                        "BGColor",
                        "HorizontalRule",
                        "/",
                        "Styles", "Format", "Font", "FontSize", "Source",
                      ]
                  }
