version: '3.8'

services: 

  db:
    image: mysql:8.0
    container_name: db_docker_symfony
    restart: always
    volumes:
        - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hugoderre
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
        - dev 
    
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
        - db
    ports:
        - 8080:80
    environment:
        PMA_HOST: db
    networks:
        - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
        - dev

  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
        - ./php/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
    restart: always
    user: '1000:1000'
    networks:
        - dev

networks:
  dev:

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
