controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
  
locale_controller:
    resource: ../../src/Controller/LocaleController.php
    type: annotation
  
security_controller:
    resource: ../../src/Controller/SecurityController.php
    type: annotation

easy_admin_controllers:
    resource: ../../src/Controller/Admin/*/*.php
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
