vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        media:
            upload_destination: 'media.storage.local'
            uri_prefix: "%uploads_uri_prefix_dev%/media"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer