vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        media:
            upload_destination: 'media.storage.local'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer