vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        media:
            upload_destination: 'media.storage.aws'
            uri_prefix: "%uploads_uri_prefix_prod%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer